# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Football365News' do
pod 'AFNetworking', '~> 3.1.0'
pod 'YYModel'
pod 'SDWebImage'
pod 'MJRefresh', '~> 3.1.9'
pod 'WMPlayer'
pod 'Masonry', '~> 1.1.0'
pod 'FCAlertView'
pod 'MBProgressHUD'

end


